### ISSUE TITLE
how to inference pj_tflite_style_transfer with mnn?

### ISSUE THREAD

**Issue by 205418367** [iwatake2222/play_with_tflite#16]

**Comment by iwatake2222** [comment]
Use the following steps:
- Convert the models into MNN format
- Select MNN as an inference framework (`InferenceHelper::MNN` )

I just created a new project for this and you can refer to https://github.com/iwatake2222/play_with_mnn/tree/master/pj_mnn_style_transfer
Conversion using the original models failed for some reasons. So, I used the models from https://github.com/PINTO0309/PINTO_model_zoo  
You can also find model conversion command here https://github.com/iwatake2222/play_with_mnn/blob/master/NOTICE.md
