### ISSUE TITLE
Segmentation fault on my own SSDV1 tflite model when running

### ISSUE THREAD

**Issue by taminhtoan2601** [iwatake2222/play_with_tflite#17]
Hello, 

Fistly, thank you for your clear instruction for running TFLite Model for object detection in C++. I met a problem when replacing your model by my own model that I trainned following the instruction of Tensflow Object Detection and exported it in .tflite, the code had an error: Segmentation fault and finished the execution. Do you have any idea for that?
Thank you in advance.
Toan.

My errors:

**pi@raspberrypi:~/play_with_tflite/pj_tflite_det_mobilenetssd_v1/build $ ./main
[InferenceHelper][52] Use TensorflowLite
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[InferenceHelperTensorflowLite][345] Input num = 1
[InferenceHelperTensorflowLite][348]     tensor[0]->name: normalized_input_image_tensor
[InferenceHelperTensorflowLite][350]     tensor[0]->dims->size[0]: 1
[InferenceHelperTensorflowLite][350]     tensor[0]->dims->size[1]: 300
[InferenceHelperTensorflowLite][350]     tensor[0]->dims->size[2]: 300
[InferenceHelperTensorflowLite][350]     tensor[0]->dims->size[3]: 3
[InferenceHelperTensorflowLite][356]     tensor[0]->type: not quantized
[InferenceHelperTensorflowLite][362] Output num = 4
[InferenceHelperTensorflowLite][365]     tensor[0]->name: TFLite_Detection_PostProcess
[InferenceHelperTensorflowLite][367]     tensor[0]->dims->size[0]: 1
[InferenceHelperTensorflowLite][367]     tensor[0]->dims->size[1]: 10
[InferenceHelperTensorflowLite][367]     tensor[0]->dims->size[2]: 4
[InferenceHelperTensorflowLite][373]     tensor[0]->type: not quantized
[InferenceHelperTensorflowLite][365]     tensor[1]->name: TFLite_Detection_PostProcess:1
[InferenceHelperTensorflowLite][367]     tensor[1]->dims->size[0]: 1
[InferenceHelperTensorflowLite][367]     tensor[1]->dims->size[1]: 10
[InferenceHelperTensorflowLite][373]     tensor[1]->type: not quantized
[InferenceHelperTensorflowLite][365]     tensor[2]->name: TFLite_Detection_PostProcess:2
[InferenceHelperTensorflowLite][367]     tensor[2]->dims->size[0]: 1
[InferenceHelperTensorflowLite][367]     tensor[2]->dims->size[1]: 10
[InferenceHelperTensorflowLite][373]     tensor[2]->type: not quantized
[InferenceHelperTensorflowLite][365]     tensor[3]->name: TFLite_Detection_PostProcess:3
[InferenceHelperTensorflowLite][367]     tensor[3]->dims->size[0]: 1
[InferenceHelperTensorflowLite][373]     tensor[3]->type: not quantized
Segmentation fault
pi@raspberrypi:~/play_with_tflite/pj_tflite_det_mobilenetssd_v1/build $**

**Comment by iwatake2222** [comment]
Can you share your model?
Maybe, you can attach your model here.

**Comment by taminhtoan2601** [comment]
Of course, please find the attachement! 
Could you share the code in order to convert to tflite model from frozen inference graph after training? I think it's problem of conversion. 
Thank you for your help! 

[detect_hand.zip](https://github.com/iwatake2222/play_with_tflite/files/6422495/detect_hand.zip)

**Comment by iwatake2222** [comment]
I tested your model and it worked after just one modification. ( I tested it on Windows, but I think the solution is the same)
The problem was label. My original code is for coco dataset, where class id 0 is background, so I incremented recognized class id.
Please delete `+ 1` at this line, and the segmentation fault should be fixed.
https://github.com/iwatake2222/play_with_tflite/blob/master/pj_tflite_det_mobilenetssd_v1/ImageProcessor/DetectionEngine.cpp#L194

![image](https://user-images.githubusercontent.com/11009876/117039241-86264080-ad43-11eb-9854-2877c2866b9b.png)

**Comment by iwatake2222** [comment]
FYI:
projects in this repository runs on many platforms including Windows and PC Linux.
So, using Visual Studio or GDB on Linux is very handy for debugging.

**Comment by taminhtoan2601** [comment]
I modified the code and the model works very fine!!! I greatly appreciate your help! You save my night!

**Comment by iwatake2222** [comment]
I'm glad to hear that!
