### ISSUE TITLE
How to download the model of yolox and yolov5 ? 

### ISSUE THREAD

**Issue by zhongwenkun886** [iwatake2222/play_with_tflite#19]
HI , How to download the file yolov5_416x416.tflite and yolox_nano_480x640.onnx ?
Thansk.

**Comment by iwatake2222** [comment]
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/059_yolov5
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/132_YOLOX

**Comment by zhongwenkun886** [comment]
thanks
