### ISSUE TITLE
How to modify the resoution of the image captured from the camera?

### ISSUE THREAD

**Issue by zhongwenkun886** [iwatake2222/play_with_tflite#25]
In this project, the resoution of the imge captured from the camera is a little low. I want get higher resoution ，so how to modify the code?
Thanks!

**Comment by iwatake2222** [comment]
You can change the resolution like this.

Where to change: https://github.com/iwatake2222/play_with_tflite/blob/master/pj_tflite_cls_mobilenet_v2/main.cpp#L50
(The main.cpp in all the project folder has the same structure)

How to change: `if (!CommonHelper::FindSourceImage(input_name, cap, 1280, 720)) {`

**Comment by zhongwenkun886** [comment]
@iwatake2222 ， I am sorry. I means modify resoution int the android app.

**Comment by iwatake2222** [comment]
Sorry, I have no idea how to modify it.

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
