### ISSUE TITLE
Best config for low FPS deep sort

### ISSUE THREAD

**Issue by zpmmehrdad** [iwatake2222/play_with_tflite#26]
Hi,

What is the best config for a video of 5 FPS? I'm using the deep sort example.

Thanks in advance

**Comment by iwatake2222** [comment]
Assuming you are asking the best config of Kalman Filter used in deep sort,
there is no best config because it depends on how the target object moves.

**Comment by iwatake2222** [comment]
I'm not sure `sometimes I get several IDs for an object` is really caused by kalman filter, but to improve tracability, increase the each values of Q https://github.com/iwatake2222/play_with_tflite/blob/master/common_helper/tracker.cpp#L149

**Comment by zpmmehrdad** [comment]
@iwatake2222 Hi,

default value is : 
const SimpleMatrix Q(kNumStatus, kNumStatus, {
        1, 0, 0, 0,    0,    0,     0,
        0, 1, 0, 0,    0,    0,     0,
        0, 0, 1, 0,    0,    0,     0,
        0, 0, 0, 1,    0,    0,     0,
        0, 0, 0, 0, 0.01,    0,     0,
        0, 0, 0, 0,    0, 0.01,     0,
        0, 0, 0, 0,    0,    0, 0.001,
        });
Could you please tell me info about values, and how much can I increase it?
