### ISSUE TITLE
DroNet with OpenCV(cv::dnn + Darknet) in C++

### ISSUE THREAD

**Issue by Abhijithyess** [iwatake2222/play_with_tflite#27]
Issue report
issue

## Environment (Hardware)
- Hardware:lenova thinkpad , CPU
- Software: ubuntu 20.1,g++9
(Please include version information)

## Project Name
pj_DroNet with OpenCV(cv::dnn + Darknet) in C++

## Issue Details
error in image_processor.cpp that ‘atanf’ is not a member of ‘std’; did you mean ‘atanh’?

## How to Reproduce
cmake ..
make

## Error Log
```
/home/abhijith/tflite/play_with_tflite/pj_tflite_det_dronet/image_processor/image_processor.cpp: In function ‘void AnalyzeFlow(cv::Mat&, std::vector<Track>&)’:
/home/abhijith/tflite/play_with_tflite/pj_tflite_det_dronet/image_processor/image_processor.cpp:157:20: error: ‘atanf’ is not a member of ‘std’; did you mean ‘atanh’?
  157 |             : std::atanf((bbox_now.y - bbox_past.y) / static_cast<float>(bbox_now.x - bbox_past.x));
      |                    ^~~~~
      |                    atanh
make[2]: *** [image_processor/CMakeFiles/ImageProcessor.dir/build.make:76: image_processor/CMakeFiles/ImageProcessor.dir/image_processor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:164: image_processor/CMakeFiles/ImageProcessor.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

## Additional Information
also find same issue in dronet original repo

**Comment by iwatake2222** [comment]
Please replace `std:atanf` for `std::atan` . You may see other similar errors. Just remove the last `f` .
