### ISSUE TITLE
how to debug in vs2019

### ISSUE THREAD

**Issue by arhow** [iwatake2222/play_with_tflite#29]
Issue report
issue

## Environment (Hardware)
- Hardware: CPU
- Software: windows10 pro

## Project Name
pj_tflite_track_deepsort

## Issue Details
```
void InferenceHelperTensorflowLite::DisplayModelInfo(const tflite::Interpreter& interpreter)
{
    /* Memo: If you get error around here in Visual Studio, please make sure you don't use Debug */

```
thanks for your sharing. you did great work.
I want to learn your code. but I can not debug in vs2019.
debug is the best way to learn code for me.
I found your comment
about here, do you know how to fix this issue, 

I try add
`#define _ITERATOR_DEBUG_LEVEL 0`
but this not work

## How to Reproduce
debug in vs2019

**Comment by iwatake2222** [comment]
Use `RelWithDebInfo`

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
