### ISSUE TITLE
读取访问权限冲突    **std::_Vector_alloc<std::_Vec_base_types<int,std::allocator<int> > >::_Myfirst**(...) 返回 0xFFFFFFFFFFFFFFFF。

### ISSUE THREAD

**Issue by fengyanWang** [iwatake2222/play_with_tflite#30]
Issue report
issue, bug, question

Hello, thank you very much for your work. This work is very good, but when I build the project according to your instructions, the following error occurred. My platform is windows10 64-bit. , The tool used is visual studio2017

## Environment (Hardware)
- Hardware: Device, CPU, GPU, etc.
- Software: OS, Compiler, etc.

window10 CPU 
visual studio 2017 MSVC x64

(Please include version information)

## Project Name
pj_xxx

pj_tflite_face_dbface  and pj_tflite_face_facemesh

## Issue Details
A clear and concise description of what the issue is.

![image](https://user-images.githubusercontent.com/36984088/143424224-325dcfe1-da26-46c1-8c02-a1eba92362cb.png)

## How to Reproduce
Steps to reproduce the behavior. Please include your cmake command.

## Error Log
```
error log
```
“main.exe”(Win32): 已加载“E:\6.tmp\tflite_pro\pj_tflite_face_dbface\build_vs2017_x64\Debug\main.exe”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\ntdll.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\kernel32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\KernelBase.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\tsafedoc64.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\ws2_32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\rpcrt4.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\user32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\win32u.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\gdi32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\gdi32full.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\msvcp_win.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\ucrtbase.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\advapi32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\msvcrt.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\sechost.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\shell32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\cfgmgr32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\SHCore.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\combase.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\bcryptprimitives.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\windows.storage.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\profapi.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\powrprof.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\umpdc.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\shlwapi.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\kernel.appcore.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\cryptsp.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\ole32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\oleaut32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\winhafnt64.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\winspool.drv”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\bcrypt.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\mpr.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\version.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\opencv_world3413d.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\comdlg32.dll”。已加载符号。
“main.exe”(Win32): 已加载“E:\6.tmp\tflite_pro\pj_tflite_face_dbface\build_vs2017_x64\libtensorflowlite.so”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\msvcp140d.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\vcomp140d.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140d.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\ucrtbased.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\propsys.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\IPHLPAPI.DLL”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.18362.900_none_2a238898466d6da2\comctl32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\concrt140d.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\mfplat.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\mf.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\mfreadwrite.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\d3d11.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\msvcp140.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140_1.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\vcruntime140_1d.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\dxgi.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\mfcore.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\crypt32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\msasn1.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\DXCore.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\ksuser.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\cryptbase.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\imm32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\winhadnt64.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\dnsapi.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\nsi.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\dtframe64.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\TIjtDrvd64.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\PdrvFlt.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\userenv.dll”。已加载符号。
[15688] DLL_PROCESS_ATTACH [E:\6.tmp\tflite_pro\pj_tflite_face_dbface\build_vs2017_x64\Debug\main.exe]
 HookLdrLoadDll 	: winspool.drv->>>>>>>PdrvFlt.dll , status=00000000
“main.exe”(Win32): 已加载“C:\Windows\System32\dtsframe64.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\mswsock.dll”。已加载符号。
HookLdrLoadDll 	: winspool.drv->>>>>>>PdrvFlt.dll , status=00000000
“main.exe”(Win32): 已加载“C:\Windows\System32\winusb.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\psapi.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\TMailHook64.dll”。无法查找或打开 PDB 文件。
“main.exe”(Win32): 已加载“C:\Windows\System32\imagehlp.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\hlink.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\RTWorkQ.dll”。已加载符号。
线程 0x3b1c 已退出，返回值为 0 (0x0)。
“main.exe”(Win32): 已加载“C:\Windows\System32\secur32.dll”。已加载符号。
“main.exe”(Win32): 已加载“C:\Windows\System32\sspicli.dll”。已加载符号。
引发了异常: 读取访问权限冲突。
**std::_Vector_alloc<std::_Vec_base_types<int,std::allocator<int> > >::_Myfirst**(...) 返回 0xFFFFFFFFFFFFFFFF。

**Comment by iwatake2222** [comment]
Can you check the followings?
 - Make sure you use Release mode in Visual Studio (You cannot use Debug mode)
 - Run another project such as pj_tflite_cls_mobilenet_v2
 - Debug the project using RelWithDebInfo in Visual Studio, and find which line causes the error

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
