### ISSUE TITLE
Segmentation fault in rpi

### ISSUE THREAD

**Issue by Abhijithyess** [iwatake2222/play_with_tflite#31]
Issue report
issue, bug, question

## Environment (Hardware)
- raspberry pi 4b ,rasbian
- Software: OS, Compiler, etc.
(Please include version information)

## Project Name
pj_ with all project

## Issue Details
working fine in laptop but failed to run in rpi.

## How to Reproduce
Steps to reproduce the behavior. Please include your cmake command.

## Error Log
```
[InferenceHelper][81] Use TensorflowLite XNNPACK Delegate
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
[InferenceHelperTensorflowLite][307] Input num = 1
[InferenceHelperTensorflowLite][310]     tensor[0]->name: input:0
[InferenceHelperTensorflowLite][312]     tensor[0]->dims->size[0]: 1
[InferenceHelperTensorflowLite][312]     tensor[0]->dims->size[1]: 256
[InferenceHelperTensorflowLite][312]     tensor[0]->dims->size[2]: 256
[InferenceHelperTensorflowLite][312]     tensor[0]->dims->size[3]: 3
[InferenceHelperTensorflowLite][318]     tensor[0]->type: not quantized
[InferenceHelperTensorflowLite][324] Output num = 1
[InferenceHelperTensorflowLite][327]     tensor[0]->name: Identity:0
[InferenceHelperTensorflowLite][329]     tensor[0]->dims->size[0]: 1
[InferenceHelperTensorflowLite][329]     tensor[0]->dims->size[1]: 6
[InferenceHelperTensorflowLite][329]     tensor[0]->dims->size[2]: 56
[InferenceHelperTensorflowLite][335]     tensor[0]->type: not quantized
Segmentation fault

```

## Additional Information
i also try to increase the swap memory upto 8 gb but no use
![Screenshot from 2021-12-06 01-04-43](https://user-images.githubusercontent.com/83626402/144761076-b25294e5-6119-4eca-869f-1ac64c7fb2e1.png)

**Comment by Abhijithyess** [comment]
![Screenshot from 2021-12-07 02-01-20](https://user-images.githubusercontent.com/83626402/144918087-3a5bd578-e1bd-4fa8-9f10-7c982eb7ed1f.png)
also unable open camer in ubuntu laptop and rpi

**Comment by iwatake2222** [comment]
- Can you  tell me your OS version?
- Does it work with still image input?
- From the second image you pasted, it looks working. What's the difference?

If it works with still image input (e.g. `./main` or `./main input.jpg` ) and the segmentation fault happens only with video/camera input, the problem is caused by OpenCV.
I suggest checking your OpenCV configuration. (Probably, avcodec or something is missed)

**Comment by Abhijithyess** [comment]
> * Can you  tell me your OS version?
"Raspbian GNU/Linux 10 (buster)"

camera issue also in ubuntu 20.1 

> * Does it work with still image input?

yess.by image input it working in both os 

okk. thank you very much for your reply

**Comment by iwatake2222** [comment]
I confirmed pj_tflite_cls_mobilenet_v2 works in my pi (Raspberry Pi 4 Model B Rev 1.2, Raspberry Pi OS (64-bit Buster) )
I suggest writing a very simple code to capture video or camera (use `cv::VideoCapture` ) and display it (use `cv::imshow` )

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
