### ISSUE TITLE
How to build 140_Ultra-Fast-Lane-Detection in Android.

### ISSUE THREAD

**Issue by Lee-Ji-won104** [iwatake2222/play_with_tflite#36]
Issue report
issue, bug, question

## Environment (Hardware)
- Hardware: 2020 m1 mac book pro, Galaxy S21(Android)
- Software: 11(Android) , osX 12

## Project Name
pj_140_Ultra-Fast-Lane-Detection

## Issue Details

(English)
1. I followed all your instructions. (Android build-https://github.com/iwatake2222/play_with_tflite/blob/master/README.md) However, nothing responded to my cell phone. The application was built normally, but it does not respond even when a button in the application is pressed.
2. I want to build the 140-Ultra Fast Lane Detection you uploaded in an Android environment, but I'm not sure because I'm an Android beginner.  I would appreciate it if you could answer or send me an email. Please go to bungae104@gmail.com.

(Japanese)
私は君の指示に全部従ったんだ。（Android build-https://github.com/iwatake2222/play_with_tflite/blob/master/README.md) でも、私の携帯電話では何も反応しなかった。） アプリケーションは正常にビルドになったが、アプリケーション中のボタンを押しても反応しない。
2. あなたがアップロードした140-Ultra Fast LaneDetectionをアンドロイド環境でビルドしたいが、アンドロイド初心者なのでよく分からない。  答えてくれたりEメールを送ってくれたりしたらとてもありがたいと思う。 bungae104@gmail.comにお願いします

**Comment by Lee-Ji-won104** [comment]
wow...amazing... I'm so fully surprised!!!! thanks for ur help...It wasn't my fault. I misunderstood your project from the start.
And now, I'm so exciting becuz of your project!!!!!! thank you!!!!!!!!!!!!!!!!

**Comment by iwatake2222** [comment]
Just updating info.
With NNAPI + quantized model, it runs faster and almost real-time speed (12FPS on Pixel4a)

https://user-images.githubusercontent.com/11009876/153705061-47c3ee65-5c9a-48da-b8b9-f273cec5569f.mp4
