### ISSUE TITLE
where is "ultra_fast_lane_detection_culane_288x800.tflite"???

### ISSUE THREAD

**Issue by Lee-Ji-won104** [iwatake2222/play_with_tflite#37]
I'm running pj_tflite_lane_ultra-fast-lane-detection. but, I can't run it. I guess there is no model file"ultra_fast_lane_detection_culane_288x800.tflite" in resource file that you uploaded...
pls tell me what 2 do....
thank you~~~ 😍

**Comment by iwatake2222** [comment]
Use https://github.com/PINTO0309/PINTO_model_zoo/blob/main/140_Ultra-Fast-Lane-Detection/download_culane.sh as desctibed at https://github.com/iwatake2222/play_with_tflite/tree/master/pj_tflite_lane_ultra-fast-lane-detection#target-environment-how-to-build-how-to-run
