### ISSUE TITLE
Stuck on bazel build tensorflow lite 2.6

### ISSUE THREAD

**Issue by Yan-Long-Huang** [iwatake2222/play_with_tflite#38]
Issue report
question

## Environment (Hardware)
- Hardware: Raspberry Pi 4, 4 GB RAM
- Software: OS: Ubuntu Server 20.04.3 LTS
- uname -a:
  Linux ubuntu 5.4.0-1050-raspi #56-Ubuntu SMP PREEMPT Thu Jan 13                                                                                                                         13:09:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
- bazel --version:
  bazel 3.7.2- (@non-git)

## Issue Details
I want to build tflite on Raspberry Pi 4 by [this page](https://github.com/iwatake2222/play_with_tflite/blob/master/00_doc/how_to_create_prebuilt_library_v2.6_linux.md)
.
And I stuck on the error that showing below:

## How to Reproduce
 a error that when I use the command:
```bazel build //tensorflow/lite:libtensorflowlite.so \
-c opt \
--config elinux_aarch64 \
--define tensorflow_mkldnn_contraction_kernel=0 \
--copt -O3 \
--strip always \
--define tflite_with_xnnpack=true
```

## Terminal & Error Log
![image](https://user-images.githubusercontent.com/73886748/153530537-6646c086-f693-407a-8ccf-809b29a14780.png)

## Additional Information
What problem is this？ How to fix it？

**Comment by iwatake2222** [comment]
I never see the error before. I confirmed the build succeed by following the note just now. I used Desktop PC (ubuntu 18.04)
Why don't you try on PC rather than Raspberry Pi ?

**Comment by Yan-Long-Huang** [comment]
Because, I want to do lane detection on a small device like the raspberry pi, and then I can put the pi that with camera in the car to do real-time lane detection.

**Comment by iwatake2222** [comment]
You can create a TensorFlow Lite library for Raspberry Pi on PC using cross compiler. Just type the same commands on PC.

**Comment by Yan-Long-Huang** [comment]
@iwatake2222 Yes, I can build TensorFlow Lite library for Raspberry Pi on PC by your document, thank you. And what should I do after that ? Is to move something that get from cross compiler to Raspberry Pi and run the lane dection app?

**Comment by iwatake2222** [comment]
- Copy `libtensorflowlite.so` in your host PC to `play_with_tflite\InferenceHelper\third_party\tflite_prebuilt\aarch64` in your raspberry pi
- Build the project
- Run the app

**Comment by iwatake2222** [comment]
By the way, pre-built library (`libtensorflowlite.so` )  for Raspberry Pi (aarch64) is already there. So, you don't need to build it by yourself.

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
