### ISSUE TITLE
fatal error: tensorflow/lite/interpreter.h: No such file or directory

### ISSUE THREAD

**Issue by Yan-Long-Huang** [iwatake2222/play_with_tflite#41]
Issue report
question

## Environment (Hardware)
* Hardware: Raspberry Pi 4, 4 GB RAM
* Software: OS: Ubuntu Server 20.04.3 LTS
* uname -a:
Linux ubuntu 5.4.0-1052-raspi #58-Ubuntu SMP PREEMPT Mon Feb 7 16:52:35 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

## Project Name
pj_tflite_lane_lanenet-lane-detection

## Issue Details

An error occurs when build:
![image](https://user-images.githubusercontent.com/73886748/157998663-41f9ddf0-0335-4319-80cf-02b1b397a174.png)

And i already put libtensorflowlite.so in /InferenceHelper/third_party/tensorflow_prebuilt/aarch64/

and tensorflow source path in /home/ubuntu/tensorflow

## How to Reproduce
In /pj_tflite_lane_lanenet-lane-detection/build directory, run
```=bash
cmake .
```
and run
```=bash
make
```

## Error Log
```
[  7%] Building CXX object image_processor/inference_helper/CMakeFiles/InferenceHelper.dir/inference_helper.cpp.o
In file included from /home/ubuntu/Codes/Project_with_tflite/InferenceHelper/inference_helper/inference_helper.cpp:35:
/home/ubuntu/Codes/Project_with_tflite/InferenceHelper/inference_helper/inference_helper_tensorflow_lite.h:27:10: fatal error: tensorflow/lite/interpreter.h: No such file or directory
   27 | #include <tensorflow/lite/interpreter.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [image_processor/inference_helper/CMakeFiles/InferenceHelper.dir/build.make:63: image_processor/inference_helper/CMakeFiles/InferenceHelper.dir/inference_helper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:221: image_processor/inference_helper/CMakeFiles/InferenceHelper.dir/all] Error 2

```

## Additional Information
What problem is this？ How to fix it？
And thank you for the repository.

**Comment by iwatake2222** [comment]
You need to run `sh InferenceHelper/third_party/download_prebuilt_libraries.sh`

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
