### ISSUE TITLE
Question: who did you traind coco_ssd_mobilenet_v1 so the model runs fast? 

### ISSUE THREAD

**Issue by muhammedakyuzlu** [iwatake2222/play_with_tflite#44]
Issue report
question

In the models folder there is a model named **"coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.tflite".** It works so fast around 20ms on my laptop and I want to add 2 classes to the model I have the datasets and I followed the tutorial on  [TFOD2](url)  with a pre-trained model "[SSD MobileNet v2 320x320](http://download.tensorflow.org/models/object_detection/tf2/20200711/ssd_mobilenet_v2_320x320_coco17_tpu-8.tar.gz)"  from [TF2 model zoo](URL)  then I quantized my model using _representative_dataset_ but my model was slow around **1250ms**. I'm wondering if you did anything that makes your model run fast

**Comment by iwatake2222** [comment]
As written in `model_information.md` in resource folder, it's from:
- https://www.tensorflow.org/lite/models/object_detection/overview
- https://storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip
    - Licensed under the Apache License, Version 2.0
