### ISSUE TITLE
convert_model_to_tflite

### ISSUE THREAD

**Issue by phamngocninh** [iwatake2222/play_with_tflite#48]
I converted the model to tflite using the yolov5 repo. Then run on your repo and get the error: Invalid input tensor info (input_1:0).
We wish to be answered. Thanks very much!!!
link: https://github.com/ultralytics/yolov5/issues/251

**Comment by iwatake2222** [comment]
You need to change tensor names.

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
