### ISSUE TITLE
Speed is slow

### ISSUE THREAD

**Issue by not-ashish** [iwatake2222/play_with_tflite#49]
Issue report
issue, bug, question:-

I ran it on my linux server but it quite slow. i ran 10 frames for a single image and i got 800ms for img processing.
Check below details :-
![image](https://user-images.githubusercontent.com/97532183/162922324-964b2c76-fcdb-42e1-9772-107bd00e2a19.png)

## Environment (Hardware)
- Hardware: Device, CPU, GPU, etc.
- Software: OS, Compiler, etc.
(Please include version information)

## Project Name
pj_xxx

## Issue Details
A clear and concise description of what the issue is.

## How to Reproduce
Steps to reproduce the behavior. Please include your cmake command.

## Error Log
```
error log
```

## Additional Information
![image](https://user-images.githubusercontent.com/97532183/162922251-0bfeb54c-58a6-4b82-900f-d60feea71f6a.png)

**Comment by iwatake2222** [comment]
Please fill out all the information.

**Comment by iwatake2222** [comment]
This issue was closed because it has been inactive.
