### ISSUE TITLE
An external symbol that cannot be resolved:"public: enum TfLiteStatus __cdecl tflite::impl::Interpreter::SetNumThreads(int)" (?SetNumThreads@Interpreter@impl@tflite@@QEAA?AW4TfLiteStatus@@H@Z)

### ISSUE THREAD

**Issue by marscep456** [iwatake2222/play_with_tflite#5]
Hi iwatake2222:
    thanks for your great works. Based on your tutorial configuration in the WIN10 environment, I had the following problems during the build the project:

    LNK2019	An external symbol that cannot be resolved "public: enum TfLiteStatus __cdecl tflite::impl::Interpreter::SetNumThreads(int)" (?SetNumThreads@Interpreter@impl@tflite@@QEAA?AW4TfLiteStatus@@H@Z)， function "public: virtual int __cdecl InferenceHelperTensorflowLite::initialize(char const *,int)" (?initialize@InferenceHelperTensorflowLite@@UEAAHPEBDH@Z) Refer to the symbol in 	main	E:\01.work\edge_tpu_c++\play_with_tflite_0811\play_with_tflite-20200811\build\pj_tflite_cls_mobilenet_v2\InferenceHelper.lib(InferenceHelperTensorflowLite.obj).

   I think maybe it is because of libtensorflowlite.so.if.lib   what should I do? 
   And the in your shared file edgetpu_prebuild not have the x64_windows file.Can you share it with us? 
   If possible,Could you send me the complete project files? I mean the files include all file in third_parry. Because I want to use the same version  tensorflow and edgetpu sound code like yours.
   
  Looking forward to your reply. thank you very much.

**Comment by iwatake2222** [comment]
Hi,
I actually have a trouble with building libedgetpu in Windows. It's still under WIP, sorry...
https://github.com/iwatake2222/play_with_tflite#for-windows-wip

**Comment by iwatake2222** [comment]
I'm sure everything should be fine if I roll back my prebuilt libtensorflow to the commit of `f394a768719a55b5c351ed1ecab2ec6f16f99dd4` . I'll update a set of libedgetpu an libtensorflow for windows when I have time (possibly this weekend).

**Comment by marscep456** [comment]
Sorry. how can I get the libtensorflow version f394a768719a55b5c351ed1ecab2ec6f16f99dd4 or the source code.On tensorflow official website is the version "https://github.com/bazelbuild/rules_closure/archive/308b05b2419edb5c8ee0471b67a40403df940149.tar.gz",  # 2019-06-13

**Comment by iwatake2222** [comment]
You can just run `git checkout f394a768719a55b5c351ed1ecab2ec6f16f99dd4`

**Comment by marscep456** [comment]
Thinks for your reply very much! I can run the demo use tensorflowlite.so . I want ask , Can I use edgetpu USB Accelerator in win10 with your projects?  I test the temp_pj_tflite_edgetpuapi_cls_mobilenet_v2 projects, It can build successfuly. But cannt run successfully.

**Comment by marscep456** [comment]
actually, error log is :

ERROR: Internal: tflite/custom_op.cc:77 tf_lite_type != kTfLiteUInt8 (2 != 3)
ERROR: Node number 0 (edgetpu-custom-op) failed to prepare.

I wonder if it's because the mobilenet_v2_1.0_224_quant_edgetpu.tflite file is build in old  version of edgetpu compiler.
but I use the same file run in python version. So I am puzzled!

**Comment by marscep456** [comment]
Thanks for your reply very much. The program is running as expectation use your method.

**Comment by iwatake2222** [comment]
yay!
