### ISSUE TITLE
Error on pj_tflite_depth_midas sample

### ISSUE THREAD

**Issue by virtualenv** [iwatake2222/play_with_tflite#50]
Issue report
Bug

## Environment (Hardware)
- Intel I7, nVidia 1080 GTX
- Windows 10 ,Visual Stduio 2019 x64

## Project Name
pj_tflite_depth_midas 

## Issue Details
It compiles just fine, generate the executable,
But when I run it, it throws me : 

[ERR: InferenceHelper][201] Unsupported inference helper type (3)
[ERR: InferenceHelper][205] Failed to create inference helper
[ERR: DepthEngine][128] Inference helper is not created
Initialization Error

## How to Reproduce
Just try to run it.

## Error Log
[ERR: InferenceHelper][201] Unsupported inference helper type (3)
[ERR: InferenceHelper][205] Failed to create inference helper
[ERR: DepthEngine][128] Inference helper is not created
Initialization Error

Thank you for the help.

**Comment by virtualenv** [comment]
Just realized that it was for TensorRT, se I believe I need to build with TensorRT to work.

**Comment by iwatake2222** [comment]
Thank you for the report. I fixed cmake setting to use TensorFlow Lite + XNNPACK by default.
Notice that you need to clean(delete) your build directory because cmake keeps previous wrong settings.
