### ISSUE TITLE
MoveNet is running very slow on video. FPS- 10 to 12

### ISSUE THREAD

**Issue by tanu1393** [iwatake2222/play_with_tflite#55]
Issue report
issue, bug, question

## Environment (Hardware)
- Hardware: CPU -AMD Ryzen 9 5950X 16-Core Processor 3.40 GHz
- Software: Windows 10, MS visual studio
(Please include version information)

## Project Name
pj_tflite_pose_movenet_multi

## Issue Details

I followed the build and compile steps for movenet on TensorflowLite. It is working but when I am passing the video as an input argument I am getting an fps of 10-12 only. I used the lightning model- movenet_multipose_256x256_lightning.tflite
 
## How to Reproduce

Perform the setup exactly as mentioned in the readme. I did a cmake using the gui and did not change the defaults

## Error Log

As in the below image, the fps is just 11.9. I have attached the original video for your reference as well. Downloaded from - https://www.pexels.com/video/three-women-posing-close-to-each-other-4723077/

![test](https://user-images.githubusercontent.com/58729206/180499144-e72e3306-c1ab-423b-a6b1-736f0ece12a2.png)

https://user-images.githubusercontent.com/58729206/180500086-f9c8428b-6377-487b-a143-2e5d5f5df1d8.mp4

**Comment by iwatake2222** [comment]
- Do you see the same FPS with still image (JPEG) input?
- What is a reasonable FPS for the model on your PC? Please tell me the reason why 10-12 FPS is "very slow"

**Comment by tanu1393** [comment]
1. Yes, I am getting same FPS when running it on a still image (12.1 FPS)
2. As mentioned on tensorflow hub "[The released variant “Lightning” can run at >30FPS on most modern laptops and detects up to 6 people simultaneously while achieving good performance](https://tfhub.dev/google/movenet/multipose/lightning/1)." That is why I thought 10-12 FPS is very slow. Could you please suggest how can I achieve the FPS around 30 , since I was planning to use it for real time pose estimation

**Comment by iwatake2222** [comment]
I checked https://storage.googleapis.com/movenet/MoveNet.MultiPose%20Model%20Card.pdf 

It looks they tested using GPU, but the project in this repo uses CPU
