### ISSUE TITLE
pj_tflite_hand_mediapipe cannot inference

### ISSUE THREAD

**Issue by jingxizc** [iwatake2222/play_with_tflite#58]
Issue report
issue, bug, question

## Environment (Hardware)
- Hardware: android phone(ROG 5s)
- Software: android

## Project Name
pj_tflite_hand_mediapipe

## Issue Details
in pj_tflite_hand_mediapipe directory, I can't find the instruction about how to use, so I download the models from mediapipe hand website(https://google.github.io/mediapipe/solutions/models.html#hands),  And also i changed the code cause the model input name and tensor_dims are not same。Then I run the demo, but cannot inference cause in UI, inference time is 0ms。So I want to know , what's your medipipe hand model? Really appreciated!!!

**Comment by iwatake2222** [comment]
https://github.com/google/mediapipe/blob/d7c287c4e95817b85c70d8457380f44c3f70a3dc/mediapipe/models/hand_landmark.tflite
https://github.com/google/mediapipe/blob/d7c287c4e95817b85c70d8457380f44c3f70a3dc/mediapipe/models/palm_detection.tflite
