### ISSUE TITLE
Compile GPU windows

### ISSUE THREAD

**Issue by JosipNizetic** [iwatake2222/play_with_tflite#8]
Hello,

I am sorry if this is not place to write. I just wanted to ask you if you know if there is possibility to run solution with GPU on windows platform  **TENSORFLOW_LITE_GPU**. I tried with your release but with no success..

Thank you very much,
Josip

**Comment by iwatake2222** [comment]
I have tried to build TensorflowLite library with GPU delegates for Windows, but it failed.
I think it's better to ask at the official repo, https://github.com/tensorflow/tensorflow .

**Comment by JosipNizetic** [comment]
Thank you very much.
I also tried but whatever I looked I could not find desktop support.

Thank you once more
